# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

p "Clearing all sesion answers..."
SessionAnswer.destroy_all

p "Clearing all revision sessions..."
RevisionSession.destroy_all

p "Clearing all concept tags..."
ConceptTag.destroy_all

p "Clearing all tags..."
Tag.destroy_all

p "Clearing all concepts..."
Concept.destroy_all

p "Clearing all documents..."
Document.destroy_all

p "Clearing all folders..."
Folder.destroy_all

p "Clearing all users..."
User.destroy_all

p "Creating new users..."

user1 = User.create!(
  first_name: "User",
  last_name: "User",
  email: "user@user.com",
  password: "password",
  password_confirmation: "password"
)

folder = Folder.create!(
  name: "Biology",
  user: user1
)

evolution = Document.create!(
  name: "Evolution",
  notes: "Evolution is change in the heritable characteristics of biological populations over successive generations.[1][2] These characteristics are the expressions of genes that are passed on from parent to offspring during reproduction. Different characteristics tend to exist within any given population as a result of mutation, genetic recombination and other sources of genetic variation.[3] Evolution occurs when evolutionary processes such as natural selection (including sexual selection) and genetic drift act on this variation, resulting in certain characteristics becoming more common or rare within a population.[4] It is this process of evolution that has given rise to biodiversity at every level of biological organisation, including the levels of species, individual organisms and molecules.[5][6]


    The scientific theory of evolution by natural selection was conceived independently by Charles Darwin and Alfred Russel Wallace in the mid-19th century and was set out in detail in Darwin's book On the Origin of Species (1859).[7] Evolution by natural selection was first demonstrated by the observation that more offspring are often produced than can possibly survive. This is followed by three observable facts about living organisms: (1) traits vary among individuals with respect to their morphology, physiology and behaviour (phenotypic variation), (2) different traits confer different rates of survival and reproduction (differential fitness) and (3) traits can be passed from generation to generation (heritability of fitness).[8] Thus, in successive generations members of a population are more likely to be replaced by the progenies of parents with favourable characteristics that have enabled them to survive and reproduce in their respective environments. In the early 20th century, other competing ideas of evolution such as mutationism and orthogenesis were refuted as the modern synthesis reconciled Darwinian evolution with classical genetics, which established adaptive evolution as being caused by natural selection acting on Mendelian genetic variation.[9]


    All life on Earth shares a last universal common ancestor (LUCA)[10][11][12] that lived approximately 3.5–3.8 billion years ago.[13] The fossil record includes a progression from early biogenic graphite,[14] to microbial mat fossils,[15][16][17] to fossilised multicellular organisms. Existing patterns of biodiversity have been shaped by repeated formations of new species (speciation), changes within species (anagenesis) and loss of species (extinction) throughout the evolutionary history of life on Earth.[18] Morphological and biochemical traits are more similar among species that share a more recent common ancestor, and can be used to reconstruct phylogenetic trees.[19][20]


    Evolutionary biologists have continued to study various aspects of evolution by forming and testing hypotheses as well as constructing theories based on evidence from the field or laboratory and on data generated by the methods of mathematical and theoretical biology. Their discoveries have influenced not just the development of biology but numerous other scientific and industrial fields, including agriculture, medicine and computer science.[21]",
  folder: folder,
  user: user1
)

alleles = Document.create!(
  name: "Alleles",
  notes: "An allele (/əˈliːl/, from German Allel and Greek ἄλλος állos “other”)[1][2] is a variant form of a given gene,[3] meaning it is one of two or more versions of a known mutation at the same place on a chromosome. It can also refer to different sequence variations for a several-hundred base-pair or more region of the genome that codes for a protein. Alleles can come in different extremes of size. At the lowest possible end one can be the single base choice of an SNP.[4] At the higher end, it can be the sequence variations for the regions of the genome that code for the same protein which can be up to several thousand base-pairs long.[5][6]


    Sometimes, different alleles can result in different observable phenotypic traits, such as different pigmentation. A notable example of this trait of color variation is Gregor Mendel's discovery that the white and purple flower colors in pea plants were the result of 'pure line' traits which could be used as a control for future experiments. However, most alleles result in little or no observable phenotypic variation.


    Most multicellular organisms have two sets of chromosomes; that is, they are diploid. In this case, the chromosomes can be paired: each pair is made up of two homologous chromosomes. If both alleles of a gene at the locus on the homologous chromosomes are the same, they and the organism are homozygous with respect to that gene. If the alleles are different, they and the organism are heterozygous with respect to that gene.",
  folder: folder,
  user: user1
)
